source 'https://rubygems.org'

gem 'jekyll'

group :jekyll_plugins do
  gem 'jekyll-seo-tag'
  gem 'jekyll-paginate'
  gem 'jekyll-email-protect'
  gem 'jekyll-target-blank'
end

gem "webrick", "~> 1.7"
gem "github-pages", "~> 227", group: :jekyll_plugins